# Stateless application specification
# The Deployment creates a single replicated Pod, indicated by the 'replicas' field
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: quickstart-instance
    migrate-for-anthos-optimization: "true"
    migrate-for-anthos-version: v1.7.5
  annotations:
    configmanagement.gke.io/namespace-selector: test-selector
  name: quickstart-instance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quickstart-instance
      migrate-for-anthos-optimization: "true"
      migrate-for-anthos-version: v1.7.5
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: quickstart-instance
        migrate-for-anthos-optimization: "true"
        migrate-for-anthos-version: v1.7.5
    spec:
      containers:
      - image: gcr.io/ws-test-anthos-hub-1623973038/quickstart-instance:6-18-2021--4-32-12
        name: quickstart-instance
        readinessProbe:
          exec:
            command:
            - /code/ready.sh
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /sys/fs/cgroup
          name: cgroups
      volumes:
      - hostPath:
          path: /sys/fs/cgroup
          type: Directory
        name: cgroups
      imagePullSecrets:
      - name: gcr-secret
status: {}

---
# Headless Service specification -
# No load-balancing, and a single cluster internal IP, only reachable from within the cluster
# The Kubernetes endpoints controller will modify the DNS configuration to return records (addresses) that point to the Pods, which are labeled with "app": "quickstart-instance"
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    migrate-for-anthos-optimization: "true"
    migrate-for-anthos-version: v1.7.5
  name: quickstart-instance
spec:
  clusterIP: None
  selector:
    app: quickstart-instance
  type: ClusterIP
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app: quickstart-instance
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
